# Generated by Django 3.1.7 on 2021-03-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLink',
            fields=[
                ('id_no', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='not have username', max_length=70)),
                ('qr_link', models.CharField(default='not have qr_link', max_length=70)),
            ],
        ),
    ]
