# Generated by Django 3.1.7 on 2021-03-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userlink_qr_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlink',
            name='qr_img',
        ),
    ]
