# Generated by Django 3.1.7 on 2021-03-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_userlink_qr_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlink',
            name='qr_title',
            field=models.CharField(default='not have qr_title', max_length=70),
        ),
    ]
